/* Generated by Cython 0.29.24 */

#ifndef __PYX_HAVE__pyorama__graphics__graphics_events
#define __PYX_HAVE__pyorama__graphics__graphics_events

#include "Python.h"

#ifndef __PYX_HAVE_API__pyorama__graphics__graphics_events

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C uint16_t __pyx_v_7pyorama_8graphics_15graphics_events_EVENT_TYPE_WINDOW;
__PYX_EXTERN_C uint16_t __pyx_v_7pyorama_8graphics_15graphics_events_EVENT_TYPE_ENTER_FRAME;

#endif /* !__PYX_HAVE_API__pyorama__graphics__graphics_events */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initgraphics_events(void);
#else
PyMODINIT_FUNC PyInit_graphics_events(void);
#endif

#endif /* !__PYX_HAVE__pyorama__graphics__graphics_events */
