cpdef enum UniformType:
    UNIFORM_TYPE_INT
    UNIFORM_TYPE_FLOAT
    UNIFORM_TYPE_VEC2
    UNIFORM_TYPE_VEC3
    UNIFORM_TYPE_VEC4
    UNIFORM_TYPE_MAT2
    UNIFORM_TYPE_MAT3
    UNIFORM_TYPE_MAT4

cpdef enum AttributeType:
    ATTRIBUTE_TYPE_INT
    ATTRIBUTE_TYPE_FLOAT
    ATTRIBUTE_TYPE_VEC2
    ATTRIBUTE_TYPE_VEC3
    ATTRIBUTE_TYPE_VEC4
    ATTRIBUTE_TYPE_MAT2
    ATTRIBUTE_TYPE_MAT3
    ATTRIBUTE_TYPE_MAT4
