from pyorama.graphics cimport *

cpdef enum ItemType:
    ITEM_TYPE_NONE
    ITEM_TYPE_WINDOW
    ITEM_TYPE_CAMERA_3D
    ITEM_TYPE_CAMERA_2D
    ITEM_TYPE_IMAGE
    ITEM_TYPE_SAMPLER
    ITEM_TYPE_TEXTURE
    ITEM_TYPE_MESH
    ITEM_TYPE_MODEL
    ITEM_TYPE_MODEL_BATCH
    ITEM_TYPE_SHADER
    ITEM_TYPE_PROGRAM
    
    ITEM_TYPE_LISTENER