/* Generated by Cython 0.29.24 */

#ifndef __PYX_HAVE__pyorama__event__input_events
#define __PYX_HAVE__pyorama__event__input_events

#include "Python.h"

#ifndef __PYX_HAVE_API__pyorama__event__input_events

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C uint16_t EVENT_TYPE_KEY_DOWN;
__PYX_EXTERN_C uint16_t EVENT_TYPE_KEY_UP;
__PYX_EXTERN_C uint16_t EVENT_TYPE_MOUSE_MOTION;
__PYX_EXTERN_C uint16_t EVENT_TYPE_MOUSE_BUTTON_DOWN;
__PYX_EXTERN_C uint16_t EVENT_TYPE_MOUSE_BUTTON_UP;
__PYX_EXTERN_C uint16_t EVENT_TYPE_MOUSE_WHEEL;
__PYX_EXTERN_C uint16_t EVENT_TYPE_JOYSTICK_AXIS;
__PYX_EXTERN_C uint16_t EVENT_TYPE_JOYSTICK_BALL;
__PYX_EXTERN_C uint16_t EVENT_TYPE_JOYSTICK_HAT;
__PYX_EXTERN_C uint16_t EVENT_TYPE_JOYSTICK_BUTTON_DOWN;
__PYX_EXTERN_C uint16_t EVENT_TYPE_JOYSTICK_BUTTON_UP;
__PYX_EXTERN_C uint16_t EVENT_TYPE_JOYSTICK_ADDED;
__PYX_EXTERN_C uint16_t EVENT_TYPE_JOYSTICK_REMOVED;

#endif /* !__PYX_HAVE_API__pyorama__event__input_events */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initinput_events(void);
#else
PyMODINIT_FUNC PyInit_input_events(void);
#endif

#endif /* !__PYX_HAVE__pyorama__event__input_events */
